# .github/workflows/graalvm.yml

name: Build with GraalVM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker-Compose
      - name: Start relay-db container
        run: docker-compose up -d relay-db

      # Step 4: Set up GraalVM
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          graalvm-version: '21.0.2'
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Verify GraalVM installation
      - name: Check GraalVM version
        run: java --version

      # Step 6: Compile with Gradle
      - name: Compile with Gradle for Native Image
        run: ./gradlew nativeOptimizedCompile
